Linear Algebra in Python

In [1]:
import numpy as np

In [2]:
#Creating vectors

In [8]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("Vector 1:", v1)
print("Vector 2:", v2)

Vector 1: [1 2 3]
Vector 2: [4 5 6]


In [6]:
v_add = v1 + v2
v_sub = v1 - v2
print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [9]:
v_scaled = v2 * 2
print(v_scaled)

[ 8 10 12]


In [13]:
v1_dot_v2 = np.dot(v1,v2)
print("The dot product of v1 and v2 is", v1_dot_v2)

The dot product of v1 and v2 is 32


# The norm of a vector

In [17]:
v1_norm = np.linalg.norm(v1)
print("The norm of v1 is", v1_norm)

The norm of v1 is 3.7416573867739413


In [28]:
#Creating matices
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,1,1],[1,1,1],[1,1,1]])
C = np.array([[4,2,6],[5,2,1]])
print(A)
print("\n",B)


matrixAdd = A + C
print("\n",matrixAdd)



[[1 2 3]
 [4 5 6]]

 [[1 1 1]
 [1 1 1]
 [1 1 1]]

 [[5 4 9]
 [9 7 7]]


# Tranposing a Matrix

In [31]:
transpose_C = C.T
print(transpose_C)
D = ([[1,2],[3,6],[8,5]])

# ixj * gxh only works if j and g are the same and the result will be ixh matrix
matrix_Multiplication = np.dot(D,C)
print("\n",matrix_Multiplication)

[[4 5]
 [2 2]
 [6 1]]

 [[14  6  8]
 [42 18 24]
 [57 26 53]]


# Solving System of Linear Equations

In [35]:
# Ax = b
# A is the coefficient matrix
# x is the unkown matrix
# b is the constant matrix

A1 = np.array([[2, 3], [4, -1]])
b = np.array([5, 3])
x = np.linalg.solve(A1,b)
print(x)

[1. 1.]


# Eigenvalues and Eigenvectors

In [39]:
A2 = np.array([[2, 1], [1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("\nEigenvectors:", eigenvectors)

Eigenvalues: [3. 1.]

Eigenvectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


# Inverse of a Matrix

In [43]:
# The inverse of a matrix 𝐴, denoted as 𝐴−1 , is the matrix that, when
# multiplied by 𝐴 results in the identity matrix:
# A * A^-1 = I
# The identity matrix is every is 0 except the diagonal that is 1s

A3 = np.array([[4,7],[2,6]])
A_inverse = np.linalg.inv(A)
print(A_inverse)

# Check to make sure
I = np.dot(A,A_inverse)
print(I)

[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[1. 0.]
 [0. 1.]]


# Singular Value Decomposition (SVD)

In [45]:
# Singular Value Decomposition (SVD) is a factorization of a matrix into threematrices:
# A=UΣV T
# Where:
# ● U and V are orthogonal matrices,
# ● Σ is a diagonal matrix of singular values.

# Define a matrix
A4 = np.array([[1, 2], [3, 4], [5, 6]])
# Perform SVD
U, sigma, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Sigma values: [3. 1.]
V^T matrix:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
