In [12]:
import numpy as np

In [13]:
def isDiagonallyDominant(A):
    for i in range(len(A)):
        diagonal = abs(A[i][i])
        other_sum = 0

        for j in range(len(A[i])):
            if i != j:
                other_sum += abs(A[i][j])

        if diagonal < other_sum:
            return False

    return True

In [14]:
A = np.array([
    [4, 1, 2],
    [1, 3, 1],
    [0, 1, 5]])

B = np.array([
    [1, 3, 2],
    [4, 1, 1],
    [2, 2, 1]])

print("Is the matrix diagonally dominant?", isDiagonallyDominant(A))
print(A,"\n")
print("Is the matrix diagonally dominant?", isDiagonallyDominant(B))
print(B)

Is the matrix diagonally dominant? True
[[4 1 2]
 [1 3 1]
 [0 1 5]] 

Is the matrix diagonally dominant? False
[[1 3 2]
 [4 1 1]
 [2 2 1]]
