In [ ]:
# LU Decomposition (aka LU Factorization) is a mathematical method
# used to factor a given square matrix A into the product of two matrices: a
# lower triangular matrix L and an upper triangular matrix U. This
# decomposition is particularly useful for solving systems of linear equations,
# inverting matrices, and computing determinants efficiently.

In [18]:
import numpy as np

In [16]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid
    # modifying the original matrix
    # modifying the original matrix
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
            for j in range(i+1, n):
                if U[i, i] == 0:
                    raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
                factor = U[j, i] / U[i, i] # Multiplier for row
                # operation
                L[j, i] = factor # Store multiplier in L
                # Update the rows of U
                for k in range(i, n):
                    U[j, k] -= factor * U[i, k]
    return L,U

In [17]:
# Example usage
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]


In [20]:
from scipy.linalg import lu

P, L, U = lu(A)
print("Matrix A:\n", A)
print("Permutation Matrix P:\n", P)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Permutation Matrix P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]]
Upper Triangular Matrix U:
 [[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]]
